CREATE TABLE diets (name text PRIMARY KEY);
CREATE TABLE goals (name text PRIMARY KEY);
CREATE TABLE allergens (name text PRIMARY KEY);
CREATE TABLE ingredient_categories (name text PRIMARY KEY);
CREATE TABLE units (code text PRIMARY KEY);
CREATE TABLE profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(35) NOT NULL CHECK(length(btrim(name)) > 0),
  weight_kg numeric(5,2) CHECK(weight_kg BETWEEN 20 AND 400),
  height_cm numeric(5,2) CHECK(height_cm BETWEEN 80 AND 250),
  goal text NOT NULL REFERENCES goals(name), diet text NOT NULL REFERENCES diets(name),
  exclusions varchar(1000) NOT NULL DEFAULT '', medical_notes varchar(2000) NOT NULL DEFAULT '',
  revision integer NOT NULL DEFAULT 0 CHECK(revision >= 0),
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE profile_allergies (
  profile_id bigint REFERENCES profiles(id) ON DELETE CASCADE,
  allergen text REFERENCES allergens(name), PRIMARY KEY(profile_id,allergen)
);
CREATE TABLE ingredients (
  id varchar(60) PRIMARY KEY, name varchar(100) NOT NULL,
  category text NOT NULL REFERENCES ingredient_categories(name),
  unit text NOT NULL REFERENCES units(code), emoji varchar(20) NOT NULL,
  animal boolean NOT NULL DEFAULT false, meat boolean NOT NULL DEFAULT false,
  position integer NOT NULL UNIQUE CHECK(position >= 0)
);
CREATE TABLE ingredient_allergens (
  ingredient_id varchar(60) REFERENCES ingredients(id) ON DELETE CASCADE,
  allergen text REFERENCES allergens(name), PRIMARY KEY(ingredient_id,allergen)
);
CREATE TABLE pantry_items (
  profile_id bigint REFERENCES profiles(id) ON DELETE CASCADE,
  ingredient_id varchar(60) REFERENCES ingredients(id), position integer NOT NULL CHECK(position >= 0),
  PRIMARY KEY(profile_id,ingredient_id), UNIQUE(profile_id,position)
);
CREATE TABLE recipes (
  id varchar(100) PRIMARY KEY, profile_id bigint REFERENCES profiles(id) ON DELETE CASCADE,
  source text NOT NULL CHECK(source IN ('catalog','gemini')),
  title varchar(100) NOT NULL CHECK(length(btrim(title)) > 0), subtitle varchar(240) NOT NULL,
  minutes integer NOT NULL CHECK(minutes BETWEEN 1 AND 60),
  category text NOT NULL CHECK(category IN ('Desayuno','Almuerzo','Cena')),
  emoji varchar(20) NOT NULL DEFAULT '🍽️', photo boolean NOT NULL DEFAULT false,
  vegan boolean NOT NULL, vegetarian boolean NOT NULL, model varchar(150),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK((source='catalog' AND profile_id IS NULL) OR (source='gemini' AND profile_id IS NOT NULL AND model IS NOT NULL))
);
CREATE TABLE recipe_ingredients (
  recipe_id varchar(100) REFERENCES recipes(id) ON DELETE CASCADE,
  ingredient_id varchar(60) REFERENCES ingredients(id), amount varchar(160) NOT NULL,
  position integer NOT NULL CHECK(position >= 0), PRIMARY KEY(recipe_id,ingredient_id), UNIQUE(recipe_id,position)
);
CREATE TABLE recipe_steps (
  recipe_id varchar(100) REFERENCES recipes(id) ON DELETE CASCADE,
  position integer NOT NULL CHECK(position BETWEEN 0 AND 9), instruction varchar(700) NOT NULL CHECK(length(btrim(instruction)) > 0),
  PRIMARY KEY(recipe_id,position)
);
CREATE TABLE recipe_allergens (
  recipe_id varchar(100) REFERENCES recipes(id) ON DELETE CASCADE,
  allergen text REFERENCES allergens(name), PRIMARY KEY(recipe_id,allergen)
);
CREATE TABLE recipe_nutrition_examples (
  recipe_id varchar(100) PRIMARY KEY REFERENCES recipes(id) ON DELETE CASCADE,
  kcal numeric NOT NULL CHECK(kcal >= 0), protein_g numeric NOT NULL CHECK(protein_g >= 0),
  carbs_g numeric NOT NULL CHECK(carbs_g >= 0), fat_g numeric NOT NULL CHECK(fat_g >= 0),
  provenance text NOT NULL CHECK(provenance='demo_unverified')
);
CREATE TABLE favorites (
  profile_id bigint REFERENCES profiles(id) ON DELETE CASCADE,
  recipe_id varchar(100) REFERENCES recipes(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(profile_id,recipe_id)
);
CREATE TABLE recipe_feedback (
  profile_id bigint REFERENCES profiles(id) ON DELETE CASCADE,
  recipe_id varchar(100) REFERENCES recipes(id) ON DELETE CASCADE,
  liked boolean NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(profile_id,recipe_id)
);
CREATE TABLE meal_plans (
  id uuid PRIMARY KEY, profile_id bigint NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  plan_date date NOT NULL, meal text NOT NULL CHECK(meal IN ('Desayuno','Almuerzo','Cena')),
  recipe_id varchar(100) NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  servings integer NOT NULL CHECK(servings BETWEEN 1 AND 4),
  created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(profile_id,plan_date,meal)
);
CREATE TABLE generation_events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  profile_id bigint NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  model varchar(150) NOT NULL, outcome varchar(50) NOT NULL,
  recipe_count integer NOT NULL CHECK(recipe_count BETWEEN 0 AND 2),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE data_imports (
  source text PRIMARY KEY, imported_at timestamptz NOT NULL DEFAULT now(),
  recipe_count integer NOT NULL CHECK(recipe_count >= 0)
);
CREATE INDEX recipes_profile_created ON recipes(profile_id,created_at DESC);
CREATE INDEX meal_plans_recipe ON meal_plans(recipe_id);
CREATE INDEX favorites_recipe ON favorites(recipe_id);
CREATE INDEX generation_events_profile_created ON generation_events(profile_id,created_at DESC);
CREATE VIEW recipe_summary AS
SELECT r.id,r.title,r.source,r.model,r.category,r.minutes,r.created_at,
  (SELECT count(*) FROM recipe_ingredients i WHERE i.recipe_id=r.id) AS ingredient_count,
  (SELECT count(*) FROM recipe_steps s WHERE s.recipe_id=r.id) AS step_count,
  (SELECT count(*) FROM favorites f WHERE f.recipe_id=r.id) AS favorites_count
FROM recipes r;
CREATE VIEW weekly_plan_details AS
SELECT p.id,p.profile_id,p.plan_date,p.meal,p.servings,r.title,r.source
FROM meal_plans p JOIN recipes r ON r.id=p.recipe_id;
