export const ingredients = [
  { id: "arroz", name: "Arroz", emoji: "🍚", category: "Granos", unit: "g" },
  {
    id: "frijoles",
    name: "Frijoles cocidos",
    emoji: "🫘",
    category: "Granos",
    unit: "g",
  },
  {
    id: "aguacate",
    name: "Aguacate",
    emoji: "🥑",
    category: "Vegetales",
    unit: "unidad",
  },
  {
    id: "tomate",
    name: "Tomate",
    emoji: "🍅",
    category: "Vegetales",
    unit: "unidad",
  },
  {
    id: "limon",
    name: "Limón",
    emoji: "🍋",
    category: "Frutas",
    unit: "unidad",
  },
  {
    id: "cilantro",
    name: "Cilantro",
    emoji: "🌿",
    category: "Vegetales",
    unit: "g",
  },
  {
    id: "huevo",
    name: "Huevo",
    emoji: "🥚",
    category: "Proteínas",
    unit: "unidad",
  },
  { id: "pollo", name: "Pollo", emoji: "🍗", category: "Proteínas", unit: "g" },
  {
    id: "tortilla",
    name: "Tortilla de maíz",
    emoji: "🫓",
    category: "Granos",
    unit: "unidad",
  },
  {
    id: "queso",
    name: "Queso fresco",
    emoji: "🧀",
    category: "Lácteos",
    unit: "g",
  },
  {
    id: "espinaca",
    name: "Espinaca",
    emoji: "🥬",
    category: "Vegetales",
    unit: "g",
  },
  { id: "avena", name: "Avena", emoji: "🌾", category: "Granos", unit: "g" },
  {
    id: "banano",
    name: "Banano",
    emoji: "🍌",
    category: "Frutas",
    unit: "unidad",
  },
  { id: "leche", name: "Leche", emoji: "🥛", category: "Lácteos", unit: "ml" },
];
export const initialPantry = [
  "arroz",
  "frijoles",
  "aguacate",
  "tomate",
  "limon",
  "cilantro",
];
export const initialProfile = {
  name: "Cristian",
  weight: "",
  height: "",
  goal: "Comer más variado",
  diet: "Sin preferencia",
  allergies: [],
  exclusions: "",
  medicalNotes: "",
};
export const allergyOptions = [
  "Leche",
  "Huevo",
  "Trigo / gluten",
  "Maní",
  "Frutos secos",
  "Soya",
  "Pescado",
  "Mariscos",
  "Sésamo",
];
export const recipes = [
  {
    id: "bowl",
    title: "Bowl de la casa",
    subtitle: "Arroz, frijoles y un toque de frescura.",
    time: 25,
    category: "Almuerzo",
    emoji: "🥗",
    photo: true,
    ingredients: [
      "arroz",
      "frijoles",
      "aguacate",
      "tomate",
      "limon",
      "cilantro",
    ],
    amounts: [
      "½ taza de arroz crudo",
      "¾ taza de frijoles cocidos",
      "½ aguacate",
      "1 tomate",
      "½ limón",
      "1 cucharada de cilantro",
    ],
    allergens: [],
    vegan: true,
    nutrition: [520, 16, 76, 17],
    steps: [
      "Cocina el arroz en agua siguiendo las instrucciones del paquete. Utiliza frijoles previamente cocidos y caliéntalos.",
      "Lava el tomate, el limón y el cilantro. Corta el tomate en cubos y el aguacate en láminas.",
      "Sirve el arroz y los frijoles en un bowl. Añade el tomate y el aguacate.",
      "Termina con el jugo de limón y el cilantro picado. Sirve recién preparado.",
    ],
  },
  {
    id: "tostadas",
    title: "Tostaditas de frijol",
    subtitle: "Crujientes, sencillas y llenas de color.",
    time: 15,
    category: "Cena",
    emoji: "🫓",
    ingredients: ["tortilla", "frijoles", "aguacate", "tomate"],
    amounts: [
      "2 tortillas de maíz",
      "½ taza de frijoles cocidos",
      "½ aguacate",
      "1 tomate",
    ],
    allergens: [],
    vegan: true,
    nutrition: [390, 12, 57, 13],
    steps: [
      "Calienta los frijoles previamente cocidos y machácalos con un poco de agua.",
      "Dora las tortillas en una sartén seca hasta que queden crujientes.",
      "Lava y corta el tomate. Corta el aguacate.",
      "Unta los frijoles sobre las tortillas y añade el tomate y el aguacate.",
    ],
  },
  {
    id: "ensalada",
    title: "Ensalada del huerto",
    subtitle: "Una pausa fresca para tu día.",
    time: 10,
    category: "Almuerzo",
    emoji: "🥑",
    ingredients: ["aguacate", "tomate", "limon", "cilantro"],
    amounts: ["½ aguacate", "2 tomates", "½ limón", "1 cucharada de cilantro"],
    allergens: [],
    vegan: true,
    nutrition: [230, 4, 18, 17],
    steps: [
      "Lava los tomates, el limón y el cilantro.",
      "Corta los tomates y el aguacate en trozos.",
      "Mezcla con el cilantro y el jugo de limón. Sirve como acompañamiento.",
    ],
  },
  {
    id: "huevos",
    title: "Huevitos con tomate",
    subtitle: "Tu desayuno de siempre, recién hecho.",
    time: 12,
    category: "Desayuno",
    emoji: "🍳",
    ingredients: ["huevo", "tomate", "tortilla"],
    amounts: ["2 huevos", "1 tomate", "2 tortillas de maíz"],
    allergens: ["Huevo"],
    vegan: false,
    vegetarian: true,
    nutrition: [320, 17, 34, 13],
    steps: [
      "Lava y pica el tomate. Ablándalo en una sartén antiadherente con un poco de agua.",
      "Añade los huevos batidos y cocina hasta que estén completamente cuajados.",
      "Calienta las tortillas y sirve junto a los huevos.",
    ],
  },
  {
    id: "avena",
    title: "Avena de buenos días",
    subtitle: "Cremosa, con banano y sin complicaciones.",
    time: 10,
    category: "Desayuno",
    emoji: "🥣",
    ingredients: ["avena", "banano", "leche"],
    amounts: ["½ taza de avena", "1 banano", "1 taza de leche"],
    allergens: ["Leche", "Trigo / gluten"],
    vegan: false,
    vegetarian: true,
    nutrition: [360, 13, 63, 7],
    steps: [
      "Calienta la leche y añade la avena.",
      "Cocina a fuego bajo, removiendo, hasta que la avena esté tierna.",
      "Pela y corta el banano. Sirve sobre la avena.",
    ],
  },
  {
    id: "quesadilla",
    title: "Quesadillas verdes",
    subtitle: "Espinaca y queso en una tortilla doradita.",
    time: 15,
    category: "Cena",
    emoji: "🌮",
    ingredients: ["tortilla", "queso", "espinaca"],
    amounts: [
      "2 tortillas de maíz",
      "50 g de queso fresco",
      "1 taza de espinaca",
    ],
    allergens: ["Leche"],
    vegan: false,
    vegetarian: true,
    nutrition: [300, 14, 32, 13],
    steps: [
      "Lava la espinaca y cocínala en una sartén con un poco de agua.",
      "Rellena las tortillas con espinaca y queso fresco.",
      "Dobla y calienta por ambos lados hasta que el queso se derrita.",
    ],
  },
];
